SPOOL c:\sql\db_create.lst


PROMPT  Казаков В.В. ИУ4-81
PROMPT Создание таблиц БД с необходимыми компонентами для АСУ

PROMPT Создание таблиц и первичных ключей
PROMPT EMPLOYEES

CREATE TABLE "ADMINISTRATOR"."EMPLOYEES" ("ID" NUMBER(10) NOT 
    NULL, "FIRST_NAME" VARCHAR2(255 byte) NOT NULL, "SECOND_NAME"
    VARCHAR2(255 byte), "POSITION" VARCHAR2(255 byte) NOT NULL, 
    "ACCEPTED_DATE" DATE NOT NULL, "FIRE_DATE" DATE, "LOGIN" 
    VARCHAR2(255 byte), 
    CONSTRAINT "C_UNIC_ID_1_1" PRIMARY KEY("ID") 
    USING INDEX  
    TABLESPACE "USERS" 
    STORAGE ( INITIAL 64K NEXT 0K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) PCTFREE 10 INITRANS 2 MAXTRANS 255,
    CONSTRAINT "C_UNUC_LOGIN" UNIQUE("LOGIN") 
    USING INDEX  
    TABLESPACE "USERS" 
    STORAGE ( INITIAL 64K NEXT 0K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) PCTFREE 10 INITRANS 2 MAXTRANS 255)
     
    TABLESPACE "USERS" PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 0K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) 
    LOGGING 

PROMPT EMPLOYEES TRIGGERS
CREATE OR REPLACE TRIGGER 
    "ADMINISTRATOR"."T_ACCEPTED_DATE_EMPLOYEES" BEFORE
INSERT ON "ADMINISTRATOR"."EMPLOYEES" FOR EACH ROW BEGIN
 :NEW.ACCEPTED_DATE := SYSDATE;
END;

CREATE OR REPLACE TRIGGER "ADMINISTRATOR"."T_EMPLOYEES_ID" BEFORE
INSERT ON "ADMINISTRATOR"."EMPLOYEES" FOR EACH ROW BEGIN  
  SELECT SEQ_EMPLOYEES_ID.NEXTVAL
  INTO :new.id
  FROM dual;
END;

CREATE TABLE "ADMINISTRATOR"."ORDERS" ("ID" NUMBER(10) NOT NULL, 
    "OBJECT_NAME" VARCHAR2(255 byte) NOT NULL, 
    "OBJECT_DESCRIPTION" VARCHAR2(255 byte), "OBJECT_TYPE" 
    VARCHAR2(255 byte) NOT NULL, "ENTERED_DATE" DATE NOT NULL, 
    "LEFT_DATE" DATE, "LOGIN" VARCHAR2(255 byte), 
    CONSTRAINT "C_UNIC_ID_1" PRIMARY KEY("ID") 
    USING INDEX  
    TABLESPACE "USERS" 
    STORAGE ( INITIAL 64K NEXT 0K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) PCTFREE 10 INITRANS 2 MAXTRANS 255)
     
    TABLESPACE "USERS" PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 0K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) 
    LOGGING 

PROMPT ORDERS TRIGGERS
CREATE OR REPLACE TRIGGER "ADMINISTRATOR"."T_ADD_TO_WAREHOUSE" 
    AFTER
UPDATE OF "LEFT_DATE" ON "ADMINISTRATOR"."ORDERS" FOR EACH ROW BEGIN
   INSERT INTO warehouse
   ( object_name,
     object_description,
     object_type )
   VALUES
   ( :new.object_name,
     :new.object_description,
     :new.object_type );
END;
CREATE OR REPLACE TRIGGER "ADMINISTRATOR"."T_ENTERED_DATE_ORDERS"
    BEFORE
INSERT ON "ADMINISTRATOR"."ORDERS" FOR EACH ROW BEGIN
 :NEW.ENTERED_DATE := SYSDATE();
END;
CREATE OR REPLACE TRIGGER "ADMINISTRATOR"."T_ORDERS_ID" BEFORE
INSERT ON "ADMINISTRATOR"."ORDERS" FOR EACH ROW BEGIN  
  SELECT SEQ_ORDERS_ID.NEXTVAL
  INTO :new.id
  FROM dual;
END;


PROMPT TASKS


CREATE TABLE "ADMINISTRATOR"."TASKS" ("ID" NUMBER(10) NOT NULL, 
    "TASK" VARCHAR2(255 byte) NOT NULL, "DESCRIPTION" 
    VARCHAR2(255 byte), "IMPORTANCE" VARCHAR2(255 byte) NOT NULL,
    "CREATE_DATE" DATE NOT NULL, "COMPLETE_DATE" DATE, "LOGIN" 
    VARCHAR2(255 byte) NOT NULL, "ADD_LOGIN" VARCHAR2(255 byte) 
    NOT NULL, 
    CONSTRAINT "C_UNIC_TASKS_ID_1_1" PRIMARY KEY("ID") 
    USING INDEX  
    TABLESPACE "USERS" 
    STORAGE ( INITIAL 64K NEXT 0K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) PCTFREE 10 INITRANS 2 MAXTRANS 255)
     
    TABLESPACE "USERS" PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 0K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) 
    LOGGING 

PROMPT TASKS TRIGGERS
CREATE OR REPLACE TRIGGER "ADMINISTRATOR"."T_CREATED_DATE_TASKS" 
    BEFORE
INSERT ON "ADMINISTRATOR"."TASKS" FOR EACH ROW BEGIN
 :NEW.CREATE_DATE := SYSDATE();
END;
CREATE OR REPLACE TRIGGER "ADMINISTRATOR"."T_TASKS_ID" BEFORE
INSERT ON "ADMINISTRATOR"."TASKS" FOR EACH ROW BEGIN  
  SELECT SEQ_TASKS_ID.NEXTVAL
  INTO :new.id
  FROM dual;
END;


PROMPT WAREHOUSE


CREATE TABLE "ADMINISTRATOR"."WAREHOUSE" ("ID" NUMBER(10) NOT 
    NULL, "OBJECT_NAME" VARCHAR2(255 byte) NOT NULL, 
    "OBJECT_DESCRIPTION" VARCHAR2(255 byte), "OBJECT_TYPE" 
    VARCHAR2(255 byte) NOT NULL, "ENTERED_DATE" DATE NOT NULL, 
    "LEFT_DATE" DATE, 
    CONSTRAINT "C_UNIC_ID" PRIMARY KEY("ID") 
    USING INDEX  
    TABLESPACE "USERS" 
    STORAGE ( INITIAL 64K NEXT 0K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) PCTFREE 10 INITRANS 2 MAXTRANS 255)
     
    TABLESPACE "USERS" PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 64K NEXT 0K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0) 
    LOGGING 

PROMPT WAREHOUSE TRIGGERS
CREATE OR REPLACE TRIGGER "ADMINISTRATOR"."T_ENTERED_DATE" BEFORE
INSERT ON "ADMINISTRATOR"."WAREHOUSE" FOR EACH ROW BEGIN
 :NEW.ENTERED_DATE := SYSDATE;
END;
CREATE OR REPLACE TRIGGER "ADMINISTRATOR"."T_WEREHOUSE_ID" BEFORE
INSERT ON "ADMINISTRATOR"."WAREHOUSE" FOR EACH ROW BEGIN  
  SELECT SEQ_WEREHOUSE_ID.NEXTVAL
  INTO :new.id
  FROM dual;
END;

PROMPT SEQUENCES

CREATE SEQUENCE "ADMINISTRATOR"."SEQ_EMPLOYEES_ID" INCREMENT BY 1
    START WITH 21 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE 
    CACHE 20 NOORDER
CREATE SEQUENCE "ADMINISTRATOR"."SEQ_ORDERS_ID" INCREMENT BY 1 
    START WITH 41 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE 
    CACHE 20 NOORDER
CREATE SEQUENCE "ADMINISTRATOR"."SEQ_TASKS_ID" INCREMENT BY 1 
    START WITH 21 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE 
    CACHE 20 NOORDER
CREATE SEQUENCE "ADMINISTRATOR"."SEQ_WEREHOUSE_ID" INCREMENT BY 1
    START WITH 121 MAXVALUE 1.0E28 MINVALUE 1 NOCYCLE 
    CACHE 20 NOORDER

PROMPT ROLES

GRANT INSERT ON "ADMINISTRATOR"."ORDERS" TO "R_CEO"; GRANT SELECT ON "ADMINISTRATOR"."ORDERS" TO "R_CEO"; GRANT UPDATE ON "ADMINISTRATOR"."ORDERS" TO "R_CEO"; GRANT INSERT ON "ADMINISTRATOR"."EMPLOYEES" TO "R_CEO"; GRANT SELECT ON "ADMINISTRATOR"."EMPLOYEES" TO "R_CEO"; GRANT UPDATE ON "ADMINISTRATOR"."EMPLOYEES" TO "R_CEO"; GRANT INSERT ON "ADMINISTRATOR"."TASKS" TO "R_CEO"; GRANT SELECT ON "ADMINISTRATOR"."TASKS" TO "R_CEO"; GRANT UPDATE ON "ADMINISTRATOR"."TASKS" TO "R_CEO";

GRANT INSERT ON "ADMINISTRATOR"."ORDERS" TO "R_WORKER"; GRANT SELECT ON "ADMINISTRATOR"."ORDERS" TO "R_WORKER"; GRANT SELECT ON "ADMINISTRATOR"."EMPLOYEES" TO "R_WORKER"; GRANT INSERT ON "ADMINISTRATOR"."TASKS" TO "R_WORKER"; GRANT SELECT ON "ADMINISTRATOR"."TASKS" TO "R_WORKER"; GRANT UPDATE ON "ADMINISTRATOR"."TASKS" TO "R_WORKER";

GRANT "DBA" TO "R_ADMINISTRATOR" WITH ADMIN OPTION; GRANT "AQ_ADMINISTRATOR_ROLE" TO "R_ADMINISTRATOR" WITH ADMIN OPTION;

GRANT INSERT ON "ADMINISTRATOR"."ORDERS" TO "R_TECHNOLOGIST"; GRANT SELECT ON "ADMINISTRATOR"."ORDERS" TO "R_TECHNOLOGIST"; GRANT UPDATE ON "ADMINISTRATOR"."ORDERS" TO "R_TECHNOLOGIST"; GRANT SELECT ON "ADMINISTRATOR"."EMPLOYEES" TO "R_TECHNOLOGIST"; GRANT INSERT ON "ADMINISTRATOR"."TASKS" TO "R_TECHNOLOGIST"; GRANT SELECT ON "ADMINISTRATOR"."TASKS" TO "R_TECHNOLOGIST"; GRANT UPDATE ON "ADMINISTRATOR"."TASKS" TO "R_TECHNOLOGIST";

GRANT INSERT ON "ADMINISTRATOR"."WAREHOUSE" TO "R_SUPPLY_MANAGER"; GRANT SELECT ON "ADMINISTRATOR"."WAREHOUSE" TO "R_SUPPLY_MANAGER"; GRANT UPDATE ON "ADMINISTRATOR"."WAREHOUSE" TO "R_SUPPLY_MANAGER"; GRANT SELECT ON "ADMINISTRATOR"."V_WAREHOUSE" TO "R_SUPPLY_MANAGER"; GRANT INSERT ON "ADMINISTRATOR"."V_WAREHOUSE" TO "R_SUPPLY_MANAGER"; GRANT UPDATE ON "ADMINISTRATOR"."V_WAREHOUSE" TO "R_SUPPLY_MANAGER"; GRANT INSERT ON "ADMINISTRATOR"."ORDERS" TO "R_SUPPLY_MANAGER"; GRANT SELECT ON "ADMINISTRATOR"."ORDERS" TO "R_SUPPLY_MANAGER"; GRANT UPDATE ON "ADMINISTRATOR"."ORDERS" TO "R_SUPPLY_MANAGER"; GRANT SELECT ON "ADMINISTRATOR"."EMPLOYEES" TO "R_SUPPLY_MANAGER"; GRANT INSERT ON "ADMINISTRATOR"."TASKS" TO "R_SUPPLY_MANAGER"; GRANT SELECT ON "ADMINISTRATOR"."TASKS" TO "R_SUPPLY_MANAGER"; GRANT UPDATE ON "ADMINISTRATOR"."TASKS" TO "R_SUPPLY_MANAGER";


SPOOL OFF
